In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import math
from datetime import *
import pygal             # Usefull for french map
from pygal.style import Style
import matplotlib.pyplot as plt
import requests
import json
import csv

%matplotlib inline

### Import Data

In [2]:
df = pd.read_csv('data.csv')
df.head(10)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (8,26,27,28,30,33,34,43,73) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,siren,nic,siret,statutDiffusionEtablissement,dateCreationEtablissement,trancheEffectifsEtablissement,anneeEffectifsEtablissement,activitePrincipaleRegistreMetiersEtablissement,dateDernierTraitementEtablissement,...,dateDebut,etatAdministratifEtablissement,enseigne1Etablissement,enseigne2Etablissement,enseigne3Etablissement,denominationUsuelleEtablissement,activitePrincipaleEtablissement,nomenclatureActivitePrincipaleEtablissement,caractereEmployeurEtablissement,codeDepartement
0,0,1807254,14,180725400014,O,1972-05-01,NaN,NaN,NaN,2009-10-02T11:01:38,...,1978-05-31,F,NaN,NaN,NaN,NaN,NaN,NaN,N,54
1,1,5410220,15,541022000015,O,NaN,NN,NaN,NaN,NaN,...,1988-03-31,F,NaN,NaN,NaN,NaN,22.02,NAP,N,80
2,2,5410345,10,541034500010,O,NaN,NaN,NaN,NaN,NaN,...,1984-12-25,F,NaN,NaN,NaN,NaN,79.06,NAP,N,80
3,3,5410394,18,541039400018,O,NaN,NN,NaN,NaN,NaN,...,1987-12-01,F,NaN,NaN,NaN,NaN,64.42,NAP,N,80
4,4,5410428,14,541042800014,O,1954-01-01,NN,NaN,NaN,NaN,...,1989-06-11,F,NaN,NaN,NaN,NaN,70.2C,NAF1993,N,80
5,5,5410436,17,541043600017,O,NaN,NaN,NaN,NaN,NaN,...,1984-12-25,F,NaN,NaN,NaN,NaN,57.11,NAP,N,80
6,6,5410485,14,541048500014,O,NaN,NaN,NaN,NaN,NaN,...,1985-12-25,F,NaN,NaN,NaN,NaN,64.42,NAP,N,80
7,7,5410527,13,541052700013,O,NaN,NaN,NaN,NaN,NaN,...,1997-07-01,F,NaN,NaN,NaN,NaN,70.2C,NAF1993,N,80
8,8,5410642,10,541064200010,O,NaN,NN,NaN,NaN,NaN,...,1991-12-31,F,NaN,NaN,NaN,NaN,64.45,NAP,N,80
9,9,5410667,17,541066700017,O,NaN,NN,NaN,NaN,NaN,...,1996-10-30,F,NaN,NaN,NaN,NaN,55.4B,NAF1993,O,80

### Load Code and Name

In [3]:
a = pd.read_excel('code_naf2.xlsx')

# 1) Density By Sector of Activity

### Selection

In [4]:
sector = '55.4B'

In [5]:
df_selection = df[(df['activitePrincipaleEtablissement'] == sector)].groupby('codeDepartement').count()

In [6]:
df_selection.head()

,Unnamed: 0,siren,nic,siret,statutDiffusionEtablissement,dateCreationEtablissement,trancheEffectifsEtablissement,anneeEffectifsEtablissement,activitePrincipaleRegistreMetiersEtablissement,dateDernierTraitementEtablissement,...,dateFin,dateDebut,etatAdministratifEtablissement,enseigne1Etablissement,enseigne2Etablissement,enseigne3Etablissement,denominationUsuelleEtablissement,activitePrincipaleEtablissement,nomenclatureActivitePrincipaleEtablissement,caractereEmployeurEtablissement
codeDepartement,,,,,,,,,,,,,,,,,,,,,
35,1,1,1,1,1,0,1,0,0,0,...,0,1,1,0,0,0,0,1,1,1
40,11,11,11,11,11,7,8,1,0,4,...,4,11,10,0,0,0,0,11,11,9
41,4,4,4,4,4,4,4,0,0,2,...,2,4,4,0,0,0,0,4,4,4
42,3,3,3,3,3,2,3,0,0,1,...,1,3,3,0,0,0,0,3,3,3
44,40,40,40,40,40,14,36,0,0,8,...,7,40,40,1,0,0,0,40,40,40

### French map : Use Librairie PYGAL

In [7]:
custom_style = Style(
  background='transparent',
  transition='200ms ease-in',
)

In [8]:
name_code_naf = a.loc[a['code'] == sector]

In [9]:
name_code_naf = name_code_naf.iloc[0,1]

In [10]:
name_code_naf

'Débits de boissons'

In [45]:
def chart():
    fr_chart = pygal.maps.fr.Departments(style=custom_style,height=450,human_readable=True)    #,legend_at_bottom=True)
    fr_chart.title = 'Density by Sector of Activity'
    fr_chart.add(name_code_naf, {x for x in zip(df_selection.index ,df_selection['siren'])})
    fr_chart.render_in_browser() # Exporte to Browser

In [46]:
chart()

file:///var/folders/v3/6rms4ljn2dzdln_l8746trf00000gn/T/tmpjjgewf45.html

# 2) Density of population by Departement

### Import Datas

In [13]:
df_pop = pd.read_csv('pop_2019.csv')

In [14]:
df_pop.head()

   Unnamed: 0  code     pop
0           0     1  653688
1           1     2  528016
2           2     3  333065
3           3     4  161980
4           4     5  141784

### French map : Use Librairie PYGAL

In [15]:
custom_style = Style(
  background='transparent',
  transition='200ms ease-in',
)

In [16]:
def chart():
    fr_chart = pygal.maps.fr.Departments(style=custom_style,height=450,human_readable=True)    #,legend_at_bottom=True)
    fr_chart.title = 'Population Density'
    fr_chart.add('In 2019', {x for x in zip(df_pop['code'] ,df_pop['pop'])})
    fr_chart.render_in_browser() # Exporte to Browser

In [17]:
chart()

file:///var/folders/v3/6rms4ljn2dzdln_l8746trf00000gn/T/tmpxu252s6b.html

## 3) Ratio Nombre d'habitant/ Nombre D'entreprise

### Create Ratio

In [18]:
ratio_list = list()
for val,val2 in zip(df_selection.index,df_selection['siren']):
    for val3,val4 in zip(df_pop['code'] ,df_pop['pop']):
        if val == val3:
            ratio_list.append((val,val2,val4))

In [19]:
ratio = list()
for i in range(len(ratio_list)):
    ratio.append((ratio_list[i][0],ratio_list[i][2]/ratio_list[i][1]))

### French map : Use Librairie PYGAL

In [20]:
def chart():
    fr_chart = pygal.maps.fr.Departments(style=custom_style,height=450,human_readable=True)    #,legend_at_bottom=True)
    fr_chart.title = 'Ratio Population/compagnie'
    fr_chart.add('Ratio In 2019', {x for x in ratio})
    fr_chart.render_in_browser() # Exporte to Browser

In [21]:
chart()

file:///var/folders/v3/6rms4ljn2dzdln_l8746trf00000gn/T/tmp3ut9aj1m.html

## 4) Date Close, less 5 years exprerience

### Choose time experience

In [22]:
date_close = 5

In [23]:
df_selection2 = df[(df['activitePrincipaleEtablissement'] == sector)]

### Convert dateDebut and dateFin to Datetime

In [24]:
df_selection2['dateDebut'] = pd.to_datetime(df_selection2['dateDebut'])
df_selection2['dateFin'] = pd.to_datetime(df_selection2['dateFin'])

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

### Value dateFin null

In [25]:
df_selection2['dateFin'].isnull().sum()

62

In [26]:
count_close = 0
for i in range(len(df)):
    try:
        if not math.isnan(df_selection2['dateFin'][i].year):
            if df_selection2['dateFin'][i].year <= df_selection2['dateDebut'][i].year + date_close:
                count_close += 1
    except:
        pass

In [27]:
print("Companies close before 5 years experience : ", count_close)

Companies close before 5 years experience :  3

## 5) Distance 50 Km

### Load Data GPS

In [28]:
gps = pd.read_csv('commune_gps.csv',sep=';',error_bad_lines=False)

In [29]:
gps

,EU_circo,code_région,nom_région,chef-lieu_région,numéro_département,nom_département,préfecture,numéro_circonscription,nom_commune,codes_postaux,code_insee,latitude,longitude,éloignement
0,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Attignat,01340,1024,46.283333,5.166667,1.21
1,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Beaupont,01270,1029,46.4,5.266667,1.91
2,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Bény,01370,1038,46.333333,5.283333,1.51
3,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Béreyziat,01340,1040,46.366667,5.05,1.71
4,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Bohas-Meyriat-Rignat,01250,1245,46.133333,5.4,1.01
5,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Bourg-en-Bresse,01000,1053,46.2,5.216667,1
6,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Buellas,01310,1065,46.2,5.133333,0.73
7,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Certines,01240,1069,46.133333,5.266667,1.97
8,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Ceyzériat,01250,1072,46.166667,5.316667,1.15
9,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Chavannes-sur-Suran,01250,1095,46.266667,5.416667,1.14
10,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Cize,01250,1106,46.2,5.433333,0.72
11,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Coligny,01270,1108,46.383333,5.35,1.81
12,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Confrançon,01310,1115,46.266667,5.066667,1.35
13,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Cormoz,01560,1124,46.45,5.233333,2.27
14,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Corveissiat,01250,1125,46.233333,5.483333,1.58
15,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Courmangoux,01370,1127,46.333333,5.366667,1.51
16,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Courtes,01560,1128,46.466667,5.1,2.31
17,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Cras-sur-Reyssouze,01340,1130,46.3,5.166667,1.31
18,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Curciat-Dongalon,01560,1139,46.466667,5.15,2.31
19,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Curtafond,01310,1140,46.266667,5.083333,1.11
20,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Dompierre-sur-Veyle,01240,1145,46.066667,5.2,1.13
21,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Domsure,01270,1147,46.416667,5.3,2.01
22,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Drom,01250,1150,46.216667,5.366667,0.8
23,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Druillat,01160,1151,46.066667,5.316667,0.1
24,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Etrez,01340,1154,46.333333,5.183333,1.51
25,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Foissiat,01340,1163,46.366667,5.183333,1.71
26,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Germagnat,01250,1172,46.316667,5.45,2.05
27,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Grand-Corent,01250,1177,46.2,5.433333,0.72
28,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Hautecourt-Romanèche,01250,1184,46.158333,5.416667,-1
29,Sud-Est,82,Rhône-Alpes,Lyon,01,Ain,Bourg-en-Bresse,1,Jasseron,01250,1195,46.216667,5.333333,0.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36810,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,4,Petite-Ile,97429,97405,NaN,NaN,NaN
36811,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,4,Sainte-Rose,97439,97419,NaN,NaN,NaN
36812,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,4,Saint-Joseph,97480,97412,NaN,NaN,NaN
36813,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,4,Saint-Philippe,97442,97417,NaN,NaN,NaN
36814,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,4,Saint-Pierre,97410,97416,NaN,NaN,NaN
36815,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,5,Bras-Panon,97412,97402,NaN,NaN,NaN
36816,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,5,La Plaine-des-Palmistes,97431,97406,NaN,NaN,NaN
36817,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,5,Saint-André,97440,97409,NaN,NaN,NaN
36818,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,5,Saint-Benoît,97470,97410,NaN,NaN,NaN
36819,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,5,Sainte-Marie,97438,97418,NaN,NaN,NaN
36820,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,5,Sainte-Suzanne,97441,97420,NaN,NaN,NaN
36821,Outre-Mer,4,La Réunion,Saint-Denis,974,Réunion,Saint-Denis,5,Salazie,97433,97421,NaN,NaN,NaN
36822,Outre-Mer,6,Saint-Pierre-et-Miquelon,Saint-Pierre,975,Saint-Pierre-et-Miquelon,Saint-Pierre,1,ACOUA,97500,97501,NaN,NaN,NaN
36823,Outre-Mer,6,Saint-Pierre-et-Miquelon,Saint-Pierre,975,Saint-Pierre-et-Miquelon,Saint-Pierre,1,BANDRABOUA,97500,97502,NaN,NaN,NaN
36824,Outre-Mer,6,Saint-Pierre-et-Miquelon,Saint-Pierre,975,Saint-Pierre-et-Miquelon,Saint-Pierre,1,BANDRELE,97500,97503,NaN,NaN,NaN
36825,Outre-Mer,6,Saint-Pierre-et-Miquelon,Saint-Pierre,975,Saint-Pierre-et-Miquelon,Saint-Pierre,1,SAINT-PIERRE,97500,97502,NaN,NaN,NaN
36826,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,BOUÉNI,97600,97604,NaN,NaN,NaN
36827,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,CHICONI,97600,97605,NaN,NaN,NaN
36828,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,CHIRONGUI,97620,97606,NaN,NaN,NaN
36829,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,DEMBENI,97660,97607,NaN,NaN,NaN
36830,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,DZAOUDZI,97610,97608,NaN,NaN,NaN
36831,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,KANI-KÉLI,97625,97609,NaN,NaN,NaN
36832,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,KOUNGOU,97690,97610,NaN,NaN,NaN
36833,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,MAMOUDZOU,97600,97611,NaN,NaN,NaN
36834,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,MTSAMBORO,97630,97612,NaN,NaN,NaN
36835,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,M'TSANGAMOUJI,97600,97613,NaN,NaN,NaN
36836,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,OUANGANI,97600,97614,NaN,NaN,NaN
36837,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,PAMANDZI,97610,97615,NaN,NaN,NaN
36838,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,SADA,97640,97616,NaN,NaN,NaN
36839,Outre-Mer,5,Mayotte,Mamoudzou,976,Mayotte,Mamoudzou,1,TSINGONI,97600,97617,NaN,NaN,NaN

### Select Siret

In [30]:
siret = 1451659500015

### Select Row from Siret

In [31]:
df_gps = df.loc[df['siret'] == siret]
df_gps['activitePrincipaleEtablissement']

9999    70.3C
Name: activitePrincipaleEtablissement, dtype: object

### Select Activity

In [32]:
activity = df_gps.iloc[0,77]
activity

'70.3C'

### Select codeCommune

In [33]:
codeCommune = int(df_gps.iloc[0,51])
codeCommune

90010

### Select Latitude

In [34]:
df_latitude_longitude = gps.loc[gps['code_insee'] == codeCommune]
lalitude = df_latitude_longitude.iloc[0,11]
lalitude

'47.633333'

### Select Longitude

In [35]:
longitude = df_latitude_longitude.iloc[0,12]
longitude

'6.866667'

### Find Latitude Longitude other Commune

In [36]:
df_selection2 = df[(df['activitePrincipaleEtablissement'] == activity)].groupby('codeCommuneEtablissement').count()
df_selection2.head()

,Unnamed: 0,siren,nic,siret,statutDiffusionEtablissement,dateCreationEtablissement,trancheEffectifsEtablissement,anneeEffectifsEtablissement,activitePrincipaleRegistreMetiersEtablissement,dateDernierTraitementEtablissement,...,dateDebut,etatAdministratifEtablissement,enseigne1Etablissement,enseigne2Etablissement,enseigne3Etablissement,denominationUsuelleEtablissement,activitePrincipaleEtablissement,nomenclatureActivitePrincipaleEtablissement,caractereEmployeurEtablissement,codeDepartement
codeCommuneEtablissement,,,,,,,,,,,,,,,,,,,,,
8043.0,1,1,1,1,1,1,1,0,0,1,...,1,1,0,0,0,0,1,1,1,1
8105.0,62,62,62,62,62,62,57,40,0,62,...,62,62,0,0,0,0,62,62,62,62
8142.0,1,1,1,1,1,1,1,0,0,1,...,1,1,0,0,0,0,1,1,1,1
8362.0,8,8,8,8,8,8,8,4,0,8,...,8,8,0,0,0,0,8,8,8,8
8409.0,9,9,9,9,9,8,9,4,0,8,...,9,9,0,0,0,0,9,9,9,9

In [37]:
list_Latitude = list()
list_Longitude = list()
list_codeCommune = list()
def find_LL():
    for val in df_selection2.index:
        df_latitude_longitude = gps.loc[gps['code_insee'] == val]
        list_Latitude.append(df_latitude_longitude.iloc[0,11])
        list_Longitude.append(df_latitude_longitude.iloc[0,12])
        list_codeCommune.append(val)

In [38]:
find_LL()

### Function Distance

In [39]:
 
from math import sin, cos, acos, pi
 
#############################################################################
def dms2dd(d, m, s):
    """Convertit un angle "degrés minutes secondes" en "degrés décimaux"
    """
    return d + m/60 + s/3600
 
#############################################################################
def dd2dms(dd):
    """Convertit un angle "degrés décimaux" en "degrés minutes secondes"
    """
    d = int(dd)
    x = (dd-d)*60
    m = int(x)
    s = (x-m)*60
    return d, m, s
 
#############################################################################
def deg2rad(dd):
    """Convertit un angle "degrés décimaux" en "radians"
    """
    return dd/180*pi
 
#############################################################################
def rad2deg(rd):
    """Convertit un angle "radians" en "degrés décimaux"
    """
    return rd/pi*180
 
#############################################################################
def distanceGPS(latA, longA, latB, longB):
    """Retourne la distance en mètres entre les 2 points A et B connus grâce à
       leurs coordonnées GPS (en radians).
    """
    # Rayon de la terre en mètres (sphère IAG-GRS80)
    RT = 6378137
    # angle en radians entre les 2 points
    S = acos(sin(latA)*sin(latB) + cos(latA)*cos(latB)*cos(abs(longB-longA)))
    # distance entre les 2 points, comptée sur un arc de grand cercle
    return S*RT
 
#############################################################################

list_final_commune = list()
list_final_dist = list()

for i in range(len(list_Latitude)):
    try:
        # cooordonnées GPS en radians du 1er point (ici, mairie de Tours)
        latA = deg2rad(float(lalitude)) # Nord
        longA = deg2rad(float(longitude)) # Est

        # cooordonnées GPS en radians du 2ème point (ici, mairie de Limoges)
        latB = deg2rad(float(list_Latitude[i])) # Nord
        longB = deg2rad(float(list_Longitude[i])) # Est

        dist = distanceGPS(latA, longA, latB, longB)
        #list_final_commune.append(int(dist))
        
        if int(dist)/1000 < 30:
            list_final_commune.append(list_codeCommune[i])
            list_final_dist.append(int(dist))
    except:
        #list_final_commune.append('nan')
        pass

In [40]:
list_final_departement = list()
for val in list_final_commune:
    df_depart = gps.loc[gps['code_insee'] == val]
    list_final_departement.append(df_depart.iloc[0,4])
    #print(list_final_departement[-1])

### French map : Use Librairie PYGAL

In [60]:
def chart():
    save = list()
    fr_chart = pygal.maps.fr.Departments(style=custom_style,height=450)    #,legend_at_bottom=True)
    fr_chart.title = 'Concurrences'
    for x in list_final_departement:
        if x not in save:
            fr_chart.add('Concurence < 30', {x : list_final_departement.count(x)})
            save.append(x)
    fr_chart.render_in_browser() # Exporte to Browser

In [61]:
chart()

file:///var/folders/v3/6rms4ljn2dzdln_l8746trf00000gn/T/tmppqd30dg0.html

### Print Commune

In [88]:
def print_concurrence():
    print("Commune à moins de 30 Km :")
    for i in range(len(list_final_commune)):
        print("\t Commune : %s, Distance : %s Km" %(list_final_commune[i],int(list_final_dist[i]/1000)))

In [89]:
print_concurrence()

Commune à moins de 30 Km :
	 Commune : 25031.0, Distance : 16 Km
	 Commune : 25043.0, Distance : 18 Km
	 Commune : 25048.0, Distance : 19 Km
	 Commune : 25057.0, Distance : 12 Km
	 Commune : 25196.0, Distance : 16 Km
	 Commune : 25230.0, Distance : 15 Km
	 Commune : 25284.0, Distance : 11 Km
	 Commune : 25304.0, Distance : 22 Km
	 Commune : 25367.0, Distance : 21 Km
	 Commune : 25388.0, Distance : 13 Km
	 Commune : 25539.0, Distance : 18 Km
	 Commune : 25547.0, Distance : 13 Km
	 Commune : 25580.0, Distance : 18 Km
	 Commune : 25614.0, Distance : 13 Km
	 Commune : 70310.0, Distance : 28 Km
	 Commune : 90010.0, Distance : 0 Km
	 Commune : 90033.0, Distance : 17 Km
	 Commune : 90075.0, Distance : 3 Km
	 Commune : 90099.0, Distance : 3 Km